from pygame import font
font.init()

WIDTH = 1080
HEIGHT = 576

FPS = 30

TILE_SIZE = 80

CARD_WIDTH = WIDTH // 6
CARD_HEIGHT = CARD_WIDTH
CARD_PADDING = CARD_WIDTH // 30

SIDE_WIDTH = CARD_WIDTH * 2 + CARD_PADDING * 3
SIDE_POS = WIDTH-SIDE_WIDTH

CITY_PADDING = WIDTH // 30

BUTTON_WIDTH = 210
BUTTON_HEIGHT = 70

NORMAL_FONT = font.SysFont("Arial", 26)