from pygame import font
font.init()

WIDTH = 1080
HEIGHT = 576

FPS = 30

TILE_SIZE = 80

CARD_WIDTH = WIDTH // 6
CARD_HEIGHT = CARD_WIDTH
CARD_PADDING = CARD_WIDTH // 30

SIDE_WIDTH = CARD_WIDTH * 2 + CARD_PADDING * 3
SIDE_POS = WIDTH-SIDE_WIDTH

CITY_PADDING = SIDE_POS // 5

# Menu
BUTTON_WIDTH = 300
BUTTON_HEIGHT = 100

# Level selector
BUTTON_SPACING = 60
BUTTON_LENGTH = 100

DISASTER_SPEED = 0.5 # second
DISASTER_DURATION = 1 # second

PANEL_WIDTH = 800
PANEL_HEIGHT = 400

NUMBER_LEVEL = 32

SMALL_FONT = font.SysFont("Agency FB", 16)
NORMAL_FONT = font.SysFont("Agency FB", 26)
LARGE_FONT = font.SysFont("Agency FB", 46)
ULTRA_THICC_FONT = font.SysFont("Agency FB", 66)
